In [1]:
# Imports
import requests
import pandas as pd
import json
import numpy as np

In [2]:
# Definindo classe FMIDataset e método get_indicators
class FMIDataset:
    """Essa classe representa os datasets que podemos extratir pela API do FMI"""
    # Criar método __init__()
    def __init__(self, database_id):
        # Criar atributos
        self.database_id = database_id

    # Definir outros métodos
    def get_indicator(self, frequency, region, indicator):
        url = f"http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/{self.database_id}/{frequency}.{region}.{indicator}"

        # Request
        response = requests.get(url).json()

        # Acessando a chave 'Series' para acessar a lista de indicadores
        indicadores = response['CompactData']['DataSet']['Series']

        # Iterando sobre as listas de indicadores
        lista_indicadores = []
        for indicador in indicadores:
            for obs in indicador['Obs']:
                dataset_info = {
                    'Código do indicador': indicador['@INDICATOR'],
                    'Localização': indicador['@REF_AREA'],
                    'Período': obs.get('@TIME_PERIOD', np.nan),
                    'Valor': obs.get('@OBS_VALUE', np.nan)
                }
                lista_indicadores.append(dataset_info)

        # Transformando em um df
        df1 = pd.DataFrame(lista_indicadores)
        return df1

In [3]:
# Implementando
base = FMIDataset('FAS')
df = base.get_indicator("A", "BR+AE+IN+AR+AO+CV", "FCRAMFHFFA_NUM+FCRODCHFFA_NUM+FCDODCHFFA_NUM+FCAODCHFFA_NUM+FCNAMFHFFA_NUM+FCNODCHFFA_NUM+FCRODCHF_PE_NUM+FCROFNMFHF_NUM+FCDODCHF_PE_NUM")
df

    Código do indicador Localização Período             Valor
0       FCDODCHF_PE_NUM          AO    2004             69980
1       FCDODCHF_PE_NUM          AO    2005             95642
2       FCDODCHF_PE_NUM          AO    2006            162834
3       FCDODCHF_PE_NUM          AO    2007            284229
4       FCDODCHF_PE_NUM          AO    2008            355057
..                  ...         ...     ...               ...
315      FCRODCHFFA_NUM          AR    2018  360.743050249196
316      FCRODCHFFA_NUM          AR    2019  361.711998497585
317      FCRODCHFFA_NUM          AR    2020  342.502574376824
318      FCRODCHFFA_NUM          AR    2021  338.026019490744
319      FCRODCHFFA_NUM          AR    2022  359.625736411706

[320 rows x 4 columns]